permissions:
  contents: write

name: AQI Tracker - Hourly Run

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Optional manual trigger from GitHub UI

jobs:
  run-aqi-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Commit and push CSV updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add levels_*.csv
          git commit -m "Update AQI CSV data" || echo "No changes to commit"
          git push
        env:
          # This gives the workflow permission to push to the repo
          # GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

